name: MacOS Test
on: [push]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      env:
        NGROK_AUTH_TOKEN: 1234567890
        MAC_USER_PASSWORD: RealKoolisw
        VNC_PASSWORD: Koolisw
        MAC_REALNAME: KooliswMac
      run: source test-os/macos.sh "$MAC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN" "$MAC_REALNAME"
